services:
  cli:
    container_name: ${ENKLUM_CONTAINER_NAME:?err}
    image: ${ENKLUM_IMAGE_NAME:?err}:${ENKLUM_IMAGE_TAG:?err}
    hostname: ${ENKLUM_CONTAINER_NAME}
    env_file:
      - .env
    working_dir: /workspace
    volumes:
      - ${ENKLUM_HOME_VOLUME:-${ENKLUM_CONTAINER_NAME}-home}:/home/${ENKLUM_USERNAME:?err}:delegated
      - ${ENKLUM_WORKSPACE_HOST_PATH:-.}:/workspace:delegated
    network_mode: host
    cap_add:
      - NET_RAW
    command: ["zsh", "-ic", "zellij"]
    stdin_open: true
    tty: true

volumes:
  ${ENKLUM_HOME_VOLUME:-${ENKLUM_CONTAINER_NAME}-home}:
