# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
# TODO Try to add above schema to default schema when using docker ?

services:
  enklum:
    container_name: ${ENKLUM_CONTAINER_NAME:-enklum-sample}
    image: ${ENKLUM_IMAGE_NAME:-ghcr.io/thomaschampagne/enklum-full}:${ENKLUM_IMAGE_TAG:-latest}
    hostname: ${ENKLUM_CONTAINER_NAME:-enklum-sample}
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /workspace
    volumes:
      - home-volume:/home/${ENKLUM_USERNAME:-smith}:delegated # TODO restore for samples
      - ${ENKLUM_WORKSPACE_HOST_PATH:-.}:/workspace:delegated
    network_mode: host
    cap_add:
      - NET_RAW
    stdin_open: true
    tty: true

volumes:
  home-volume:
    name: ${ENKLUM_HOME_VOLUME:-enklum-sample-home}
