[tools]
# Base Cli Tools
sd = "latest"
ripgrep = "latest"
fzf = "latest"
zoxide = "latest"
starship = "latest"

# Base Tools
helix = "latest"
neovim = "latest"
lazygit = "latest"
yazi = "latest"
zellij = "latest"
opencode = "latest"

# Base LSP
marksman = "latest"
